//! `package.lock.toml` schema, parser, writer, and tamper-check.
//!
//! Implements §7 of `corpus/edda-codex/language/08-packages.md`: the
//! lockfile schema, the flat `deps` field, and the `lockfile_hash` trailer
//! that detects hand-edits.
//!
//! The lockfile is generated by the resolver/package manager — callers must
//! not hand-edit it. The `lockfile_hash` trailer is a BLAKE3 digest over the
//! canonical encoding of every `[[rune]]` entry; any mutation of the entries
//! after generation causes `load` / `parse` to return `Err(LockfileTampered)`.
//!
//! # Canonical encoder for the `lockfile_hash` trailer
//!
//! Routes through [`edda_cache::hash_bytes`] — the workspace's single BLAKE3
//! binding. The inline encoder below is intentionally minimal and covers only
//! the fixed `[[rune]]` schema (twelve sorted keys). A follow-up commit will
//! migrate this to the now-landed `edda-mimir-canonical` crate.
//!
//! # TODO(canonical-migration)
//! `edda-mimir-canonical` has landed but exposes a generic
//! `edda_mimir_canonical::encode(&Value)` rather than a dedicated rune-entry
//! encoder. Migrating means lowering each [`LockfileEntry`] to a canonical
//! `Value` and routing it through `encode`, then removing `encode_entry_canonical`.

use std::io;
use std::path::Path;

use edda_cache::hash_bytes;
use edda_diag::{Diagnostic, DiagnosticClass, Diagnostics, LintConfig};
use edda_span::{FileId, SourceMap, Span};

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// In-memory representation of a `package.lock.toml` file.
///
/// Generated by the package resolver; not for hand-editing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lockfile {
    /// Every direct and transitive rune dependency, in resolved-dependency
    /// order.
    pub runes: Vec<LockfileEntry>,
    /// The `[lockfile_meta]` table containing the tamper-detection trailer.
    pub meta: LockfileMeta,
}

/// One entry in `[[rune]]`. Records a single rune dependency's pinned hashes,
/// publisher key, and publisher signature.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockfileEntry {
    /// rune package name.
    pub name: String,
    /// Pinned semver string (e.g. `"1.4.2"`).
    pub version: String,
    /// Registry source (`"mimir.edda.dev"`, `"file:///path"`,
    /// or `"https://..."`).
    pub source: String,
    /// BLAKE3 hash of the full `.rune` archive bytes: `"blake3:<hex>"`.
    pub rune_hash: String,
    /// BLAKE3 hash of the surface (public API) artifact: `"blake3:<hex>"`.
    pub surface_hash: String,
    /// BLAKE3 hash of the effect-row manifest: `"blake3:<hex>"`.
    pub effect_hash: String,
    /// Publisher's ed25519 public key: `"ed25519:<pem-or-hex>"`.
    pub publisher_key: String,
    /// Publisher's ed25519 signature over the archive: `"ed25519:<hex>"`.
    pub publisher_sig: String,
    /// Flat transitive dependency list — rune names only, no versions.
    pub deps: Vec<String>,
}

/// The `[lockfile_meta]` block of a `package.lock.toml`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockfileMeta {
    /// BLAKE3 over the canonical encoding of all `[[rune]]` entries in
    /// lockfile order. Computed by `write` and re-verified by `load`/`parse`.
    pub lockfile_hash: String,
}

/// Error returned by [`load`] and [`parse`].
#[derive(Debug)]
pub enum LockfileError {
    /// I/O failure reading the file.
    Io(io::Error),
    /// TOML syntax error.
    Parse(String),
    /// Trailer `lockfile_hash` mismatches the recomputed digest.
    /// A [`DiagnosticClass::LockfileTampered`] diagnostic was pushed to `diags`.
    Tampered,
    /// Structural failure beyond TOML parse (missing required field or table).
    Malformed(String),
}

impl std::fmt::Display for LockfileError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LockfileError::Io(e) => write!(f, "I/O error: {}", e),
            LockfileError::Parse(s) => write!(f, "TOML parse error: {}", s),
            LockfileError::Tampered => write!(f, "lockfile_hash trailer mismatch (tampered)"),
            LockfileError::Malformed(s) => write!(f, "malformed lockfile: {}", s),
        }
    }
}

impl std::error::Error for LockfileError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            LockfileError::Io(e) => Some(e),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Read and validate a `package.lock.toml` from disk.
///
/// Returns:
/// - `Ok(Lockfile)` if the file parses and the `lockfile_hash` trailer verifies.
/// - `Err(LockfileError::Tampered)` if the trailer mismatches; a
///   `LockfileTampered` diagnostic is pushed to `diags` at `Span::DUMMY`.
/// - `Err(LockfileError::Parse(_))` on TOML syntax error.
/// - `Err(LockfileError::Io(_))` on read failure.
pub fn load(
    path: &Path,
    source_map: &SourceMap,
    diags: &mut Diagnostics,
    lint_cfg: &LintConfig,
) -> Result<Lockfile, LockfileError> {
    let content = std::fs::read_to_string(path).map_err(LockfileError::Io)?;
    let file = source_map.add_file(path.to_path_buf(), content);
    let src = source_map.file_content(file);
    parse(src, file, diags, lint_cfg)
}

/// Parse a `package.lock.toml` from a string without disk I/O.
///
/// Same validation contract as [`load`]: parses, then verifies the
/// `lockfile_hash` trailer. On mismatch, pushes a `LockfileTampered`
/// diagnostic and returns `Err(Tampered)`.
pub fn parse(
    src: &str,
    file: FileId,
    diags: &mut Diagnostics,
    lint_cfg: &LintConfig,
) -> Result<Lockfile, LockfileError> {
    let table: toml::Table = src
        .parse()
        .map_err(|e: toml::de::Error| LockfileError::Parse(e.to_string()))?;

    let runes = parse_runes(&table)?;
    let meta = parse_meta(&table)?;

    let expected = compute_trailer(&runes);
    if meta.lockfile_hash != expected {
        push_tampered_diag(diags, lint_cfg, file, Span::DUMMY, &expected, &meta.lockfile_hash);
        return Err(LockfileError::Tampered);
    }

    Ok(Lockfile { runes, meta })
}

/// Write a `Lockfile` to disk in canonical form.
///
/// Computes the `lockfile_hash` trailer via [`compute_trailer`] over the
/// `[[rune]]` entries (not over the final file bytes) and emits it as the
/// `[lockfile_meta]` block. The written file passes tamper-detection on
/// subsequent [`load`] / [`parse`] calls.
pub fn write(lockfile: &Lockfile, path: &Path) -> Result<(), LockfileError> {
    let content = render_lockfile(lockfile);
    std::fs::write(path, content.as_bytes()).map_err(LockfileError::Io)
}

/// Compute the `lockfile_hash` trailer over the canonical encoding of the
/// `[[rune]]` entries.
///
/// The hash input is the concatenation of all entries' canonical bytes in
/// lockfile order (NOT sorted). Each entry's keys are sorted lexicographically
/// inside its block per §5 canonical encoding rules.
///
/// Exposed publicly so callers can sanity-check hand-built `Lockfile` values.
pub fn compute_trailer(runes: &[LockfileEntry]) -> String {
    let mut buf: Vec<u8> = Vec::with_capacity(runes.len() * 256);
    for entry in runes {
        encode_entry_canonical(entry, &mut buf);
    }
    let hash = hash_bytes(&buf);
    format!("blake3:{}", hash)
}

// ---------------------------------------------------------------------------
// Internal: TOML parsing helpers
// ---------------------------------------------------------------------------

/// Parse the `[[rune]]` array from a top-level TOML table.
fn parse_runes(table: &toml::Table) -> Result<Vec<LockfileEntry>, LockfileError> {
    let raw = match table.get("rune") {
        None => return Ok(Vec::new()),
        Some(v) => v,
    };

    let arr = raw.as_array().ok_or_else(|| {
        LockfileError::Malformed("`rune` must be an array of tables".into())
    })?;

    arr.iter()
        .enumerate()
        .map(|(i, item)| parse_one_entry(item, i))
        .collect()
}

/// Parse one `[[rune]]` entry from a TOML value.
fn parse_one_entry(value: &toml::Value, idx: usize) -> Result<LockfileEntry, LockfileError> {
    let t = value.as_table().ok_or_else(|| {
        LockfileError::Malformed(format!("rune[{}] must be a table", idx))
    })?;

    let get_str = |key: &str| -> Result<String, LockfileError> {
        t.get(key)
            .and_then(|v| v.as_str())
            .map(|s| s.to_owned())
            .ok_or_else(|| {
                LockfileError::Malformed(format!(
                    "rune[{}]: missing or non-string field `{}`", idx, key
                ))
            })
    };

    let name = get_str("name")?;
    let version = get_str("version")?;
    let source = get_str("source")?;
    let rune_hash = get_str("rune_hash")?;
    let surface_hash = get_str("surface_hash")?;
    let effect_hash = get_str("effect_hash")?;
    let publisher_key = get_str("publisher_key")?;
    let publisher_sig = get_str("publisher_sig")?;

    let deps = match t.get("deps") {
        None => Vec::new(),
        Some(v) => {
            let arr = v.as_array().ok_or_else(|| {
                LockfileError::Malformed(format!("rune[{}].deps must be an array", idx))
            })?;
            arr.iter()
                .map(|item| {
                    item.as_str()
                        .map(|s| s.to_owned())
                        .ok_or_else(|| {
                            LockfileError::Malformed(format!(
                                "rune[{}].deps: every element must be a string", idx
                            ))
                        })
                })
                .collect::<Result<Vec<_>, _>>()?
        }
    };

    Ok(LockfileEntry {
        name,
        version,
        source,
        rune_hash,
        surface_hash,
        effect_hash,
        publisher_key,
        publisher_sig,
        deps,
    })
}

/// Parse the `[lockfile_meta]` table.
fn parse_meta(table: &toml::Table) -> Result<LockfileMeta, LockfileError> {
    let meta_val = table.get("lockfile_meta").ok_or_else(|| {
        LockfileError::Malformed("missing `[lockfile_meta]` table".into())
    })?;

    let meta_table = meta_val.as_table().ok_or_else(|| {
        LockfileError::Malformed("`lockfile_meta` must be a table".into())
    })?;

    let lockfile_hash = meta_table
        .get("lockfile_hash")
        .and_then(|v| v.as_str())
        .map(|s| s.to_owned())
        .ok_or_else(|| {
            LockfileError::Malformed(
                "`lockfile_meta.lockfile_hash` is missing or not a string".into(),
            )
        })?;

    Ok(LockfileMeta { lockfile_hash })
}

// ---------------------------------------------------------------------------
// Internal: canonical encoder for the trailer
// ---------------------------------------------------------------------------

/// Canonical byte encoding of one `[[rune]]` entry for the `lockfile_hash`
/// input. Keys are sorted lex. Concatenate all entries in lockfile order to
/// form the full hash input.
///
/// TODO(canonical-migration): `edda-mimir-canonical` has landed; replace this
/// inline encoder by lowering the entry to a canonical `Value` and routing it
/// through `edda_mimir_canonical::encode`.
fn encode_entry_canonical(entry: &LockfileEntry, buf: &mut Vec<u8>) {
    // Keys in lexicographic order.
    write_canonical_kv(buf, "deps", entry.deps.iter().map(String::as_str));
    write_canonical_str(buf, "effect_hash", &entry.effect_hash);
    write_canonical_str(buf, "name", &entry.name);
    write_canonical_str(buf, "publisher_key", &entry.publisher_key);
    write_canonical_str(buf, "publisher_sig", &entry.publisher_sig);
    write_canonical_str(buf, "rune_hash", &entry.rune_hash);
    write_canonical_str(buf, "source", &entry.source);
    write_canonical_str(buf, "surface_hash", &entry.surface_hash);
    write_canonical_str(buf, "version", &entry.version);
    buf.push(b'\n');
}

/// Append `key = "value"\n` to `buf`.
fn write_canonical_str(buf: &mut Vec<u8>, key: &str, value: &str) {
    buf.extend_from_slice(key.as_bytes());
    buf.extend_from_slice(b" = ");
    buf.push(b'"');
    buf.extend_from_slice(value.as_bytes());
    buf.push(b'"');
    buf.push(b'\n');
}

/// Append `key = ["v1", "v2", ...]\n` to `buf`.
fn write_canonical_kv<'a>(
    buf: &mut Vec<u8>,
    key: &str,
    values: impl Iterator<Item = &'a str>,
) {
    buf.extend_from_slice(key.as_bytes());
    buf.extend_from_slice(b" = [");
    let mut first = true;
    for v in values {
        if !first {
            buf.extend_from_slice(b", ");
        }
        first = false;
        buf.push(b'"');
        buf.extend_from_slice(v.as_bytes());
        buf.push(b'"');
    }
    buf.push(b']');
    buf.push(b'\n');
}

// ---------------------------------------------------------------------------
// Internal: writer
// ---------------------------------------------------------------------------

/// Render a `Lockfile` to a canonical TOML string.
fn render_lockfile(lockfile: &Lockfile) -> String {
    let trailer = compute_trailer(&lockfile.runes);
    let mut out = String::new();

    for entry in &lockfile.runes {
        out.push_str("[[rune]]\n");
        out.push_str(&format!("name           = {:?}\n", entry.name));
        out.push_str(&format!("version        = {:?}\n", entry.version));
        out.push_str(&format!("source         = {:?}\n", entry.source));
        out.push_str(&format!("rune_hash      = {:?}\n", entry.rune_hash));
        out.push_str(&format!("surface_hash   = {:?}\n", entry.surface_hash));
        out.push_str(&format!("effect_hash    = {:?}\n", entry.effect_hash));
        out.push_str(&format!("publisher_key  = {:?}\n", entry.publisher_key));
        out.push_str(&format!("publisher_sig  = {:?}\n", entry.publisher_sig));
        let deps_str = entry
            .deps
            .iter()
            .map(|d| format!("{:?}", d))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("deps           = [{}]\n", deps_str));
        out.push('\n');
    }

    out.push_str("[lockfile_meta]\n");
    out.push_str(&format!("lockfile_hash  = {:?}\n", trailer));

    out
}

// ---------------------------------------------------------------------------
// Internal: diagnostic emission
// ---------------------------------------------------------------------------

/// Push a `LockfileTampered` diagnostic to `diags`.
fn push_tampered_diag(
    diags: &mut Diagnostics,
    lint_cfg: &LintConfig,
    _file: FileId,
    span: Span,
    expected: &str,
    actual: &str,
) {
    let severity = lint_cfg.effective(DiagnosticClass::LockfileTampered);
    let msg = format!(
        "package.lock.toml has been tampered: \
         lockfile_hash trailer mismatch (expected {}, found {})",
        expected, actual
    );
    diags.push(Diagnostic::new(
        DiagnosticClass::LockfileTampered,
        severity,
        span,
        msg,
    ));
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use edda_diag::LintConfig;
    use edda_span::SourceMap;
    use std::path::PathBuf;

    fn dummy_lint_cfg() -> LintConfig {
        LintConfig::default()
    }

    fn dummy_source_map() -> SourceMap {
        SourceMap::new()
    }

    fn dummy_file(sm: &SourceMap) -> FileId {
        sm.add_file(PathBuf::from("package.lock.toml"), String::new())
    }

    fn make_entry(name: &str) -> LockfileEntry {
        LockfileEntry {
            name: name.to_owned(),
            version: "1.0.0".to_owned(),
            source: "mimir.edda.dev".to_owned(),
            rune_hash: "blake3:aabbcc".to_owned(),
            surface_hash: "blake3:ddeeff".to_owned(),
            effect_hash: "blake3:112233".to_owned(),
            publisher_key: "ed25519:pubkey01".to_owned(),
            publisher_sig: "ed25519:sig0101".to_owned(),
            deps: vec![],
        }
    }

    fn make_lockfile_text(entries: &[LockfileEntry]) -> String {
        let lf = Lockfile {
            runes: entries.to_vec(),
            meta: LockfileMeta {
                lockfile_hash: compute_trailer(entries),
            },
        };
        render_lockfile(&lf)
    }

    #[test]
    fn parse_minimal_lockfile_with_one_rune_round_trips() {
        let entry = make_entry("regex");
        let text = make_lockfile_text(&[entry.clone()]);

        let sm = dummy_source_map();
        let file = dummy_file(&sm);
        let mut diags = Diagnostics::new();
        let cfg = dummy_lint_cfg();

        let lf = parse(&text, file, &mut diags, &cfg).expect("should parse");
        assert!(diags.is_empty());
        assert_eq!(lf.runes.len(), 1);
        assert_eq!(lf.runes[0].name, "regex");
        assert_eq!(lf.runes[0].version, "1.0.0");

        // Round-trip: write back and parse again.
        let rendered = render_lockfile(&lf);
        let lf2 = parse(&rendered, file, &mut diags, &cfg).expect("second parse should succeed");
        assert_eq!(lf.runes, lf2.runes);
        assert_eq!(lf.meta, lf2.meta);
    }

    #[test]
    fn parse_empty_lockfile_admitted() {
        let text = make_lockfile_text(&[]);
        let sm = dummy_source_map();
        let file = dummy_file(&sm);
        let mut diags = Diagnostics::new();
        let cfg = dummy_lint_cfg();

        let lf = parse(&text, file, &mut diags, &cfg).expect("empty lockfile must parse");
        assert!(diags.is_empty());
        assert!(lf.runes.is_empty());

        // Trailer over empty input is stable.
        let h1 = compute_trailer(&[]);
        let h2 = compute_trailer(&[]);
        assert_eq!(h1, h2);
        assert_eq!(lf.meta.lockfile_hash, h1);
    }

    #[test]
    fn write_emits_canonical_lockfile_hash() {
        let entry = make_entry("serde");
        let lf = Lockfile {
            runes: vec![entry.clone()],
            meta: LockfileMeta {
                lockfile_hash: compute_trailer(&[entry.clone()]),
            },
        };

        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("package.lock.toml");
        write(&lf, &path).expect("write must succeed");

        let sm = SourceMap::new();
        let mut diags = Diagnostics::new();
        let cfg = dummy_lint_cfg();
        let loaded = load(&path, &sm, &mut diags, &cfg).expect("load must succeed");

        assert!(diags.is_empty());
        assert_eq!(loaded.meta.lockfile_hash, lf.meta.lockfile_hash);
        assert_eq!(loaded.runes[0].name, "serde");
    }

    #[test]
    fn parse_rejects_missing_lockfile_hash() {
        // TOML with [[rune]] entries but no [lockfile_meta].
        let text = "[[rune]]\nname = \"foo\"\nversion = \"1.0.0\"\n\
                    source = \"mimir.edda.dev\"\n\
                    rune_hash = \"blake3:aa\"\nsurface_hash = \"blake3:bb\"\n\
                    effect_hash = \"blake3:cc\"\npublisher_key = \"ed25519:pk\"\n\
                    publisher_sig = \"ed25519:sig\"\ndeps = []\n";

        let sm = dummy_source_map();
        let file = dummy_file(&sm);
        let mut diags = Diagnostics::new();
        let cfg = dummy_lint_cfg();

        let result = parse(text, file, &mut diags, &cfg);
        assert!(
            matches!(result, Err(LockfileError::Malformed(_))),
            "missing lockfile_meta must produce Malformed"
        );
    }

    #[test]
    fn parse_emits_lockfile_tampered_on_trailer_mismatch() {
        let entry = make_entry("tokio");
        // Build valid text then mutate rune_hash to simulate a hand-edit.
        let mut text = make_lockfile_text(&[entry]);
        // Corrupt rune_hash after generating.
        text = text.replace("rune_hash      = \"blake3:aabbcc\"",
                            "rune_hash      = \"blake3:TAMPERED\"");

        let sm = dummy_source_map();
        let file = dummy_file(&sm);
        let mut diags = Diagnostics::new();
        let cfg = dummy_lint_cfg();

        let result = parse(&text, file, &mut diags, &cfg);
        assert!(matches!(result, Err(LockfileError::Tampered)));
        assert_eq!(diags.len(), 1);
        assert_eq!(diags.iter().next().unwrap().class, DiagnosticClass::LockfileTampered);
    }

    #[test]
    fn parse_emits_lockfile_tampered_on_added_rune_entry() {
        let entry = make_entry("syn");
        // Generate trailer for 1 entry, then inject a second entry before [lockfile_meta].
        let text = make_lockfile_text(&[entry.clone()]);
        let extra = "[[rune]]\n\
                     name           = \"quote\"\n\
                     version        = \"1.0.0\"\n\
                     source         = \"mimir.edda.dev\"\n\
                     rune_hash      = \"blake3:aabbcc\"\n\
                     surface_hash   = \"blake3:ddeeff\"\n\
                     effect_hash    = \"blake3:112233\"\n\
                     publisher_key  = \"ed25519:pubkey01\"\n\
                     publisher_sig  = \"ed25519:sig0101\"\n\
                     deps           = []\n\n";
        let injected = text.replace("[lockfile_meta]", &format!("{}\n[lockfile_meta]", extra));

        let sm = dummy_source_map();
        let file = dummy_file(&sm);
        let mut diags = Diagnostics::new();
        let cfg = dummy_lint_cfg();

        let result = parse(&injected, file, &mut diags, &cfg);
        assert!(matches!(result, Err(LockfileError::Tampered)));
        assert_eq!(diags.len(), 1);
        assert_eq!(diags.iter().next().unwrap().class, DiagnosticClass::LockfileTampered);
    }

    #[test]
    fn write_then_load_round_trip() {
        let a = make_entry("anyhow");
        let b = {
            let mut e = make_entry("thiserror");
            e.deps = vec!["anyhow".to_owned()];
            e
        };
        let lf = Lockfile {
            runes: vec![a.clone(), b.clone()],
            meta: LockfileMeta {
                lockfile_hash: compute_trailer(&[a.clone(), b.clone()]),
            },
        };

        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("package.lock.toml");
        write(&lf, &path).expect("write must succeed");

        let sm = SourceMap::new();
        let mut diags = Diagnostics::new();
        let cfg = dummy_lint_cfg();
        let loaded = load(&path, &sm, &mut diags, &cfg).expect("load must succeed");

        assert!(diags.is_empty());
        assert_eq!(loaded.runes, lf.runes);
        assert_eq!(loaded.meta, lf.meta);
    }

    #[test]
    fn compute_trailer_is_deterministic() {
        let entries = vec![make_entry("async-std"), make_entry("futures")];
        let h1 = compute_trailer(&entries);
        let h2 = compute_trailer(&entries);
        assert_eq!(h1, h2);
        assert!(h1.starts_with("blake3:"));
    }
}
